# Generated by Django 4.0 on 2022-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Product', models.CharField(max_length=10)),
                ('Product_name', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(max_length=100)),
                ('Detail_product', models.TextField(max_length=1000)),
                ('Price', models.FloatField(max_length=10)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
