# Generated by Django 4.0 on 2022-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CactusShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
