# Generated by Django 4.0 on 2022-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CactusShop', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='Quantityy',
            field=models.IntegerField(default=0),
        ),
    ]
