# Generated by Django 4.0 on 2022-01-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CactusShop', '0003_remove_product_quantity_product_quantityy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Quantityy',
            new_name='Quantities',
        ),
    ]
