# Generated by Django 4.0 on 2022-01-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CactusShop', '0005_remove_product_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
