# Generated by Django 4.0 on 2022-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CactusShop', '0006_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=225)),
                ('Password', models.CharField(max_length=8)),
                ('Email', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductTypeId', models.CharField(max_length=10)),
                ('priority', models.IntegerField(choices=[(0, 'Fill in'), (1, 'Cactus'), (2, 'Pot'), (3, 'Potting Soil'), (4, 'Decaration'), (5, 'Fertilizer'), (6, 'Seed')], default=0)),
            ],
        ),
    ]
